# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Oz∀n∈ℝ
tagline:          'My Projects'
description:      'A compilation of all my published notes,
                  projects, and articles.'
url:              https://ozanerhansha.github.io
baseurl:          /

author:
  name:           'Ozaner Hansha'
  url:            https://ozanerhansha.github.io

paginate:         5
plugins:          [jekyll-paginate]
