# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Oz∀n∈ℝ
tagline:          'My Projects'
description:      'A compilation of my notes,
                  projects, and articles.'
url:              https://ozanerhansha.github.io
baseurl:          /

author:
  name:           'Ozaner Hansha'
  url:            https://ozanerhansha.github.io

paginate:         5
plugins:          [jekyll-paginate]

excerpt_separator: <!--more-->  # you can specify your own separator, of course.