# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        /:categories/:title/

# Setup
# Oz∀n∈ℝ
title:            Ozaner
tagline:          Recent Posts
description:      'A compilation of my notes,
                  projects, and articles.'
url:              https://ozanerhansha.github.io
baseurl:          /

author:
  name:           'Ozaner Hansha'
  url:            https://ozanerhansha.github.io

paginate:         5
plugins:          [jekyll-paginate]

excerpt_separator: <!--more-->

exclude: ['/hw/*.md']